name: SavingsDai
description: Tokenized Vaults
networks:
- id: 1
  rpc_config:
    url: https://eth.merkle.io
  start_block: 16428133
  contracts:
  - name: SavingsDai
    address:
    - 0x83F20F44975D03b1b09e64809B757c47f942BEeA
    abi_file_path: null
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
      requiredEntities:
      - name: EventsSummary
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
      requiredEntities:
      - name: EventsSummary
    - event: Transfer(address indexed from, address indexed to, uint256 value)
      requiredEntities:
      - name: EventsSummary
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
      requiredEntities:
      - name: EventsSummary
